### ISSUE TITLE
API error when (succesfully) deleting order

### ISSUE THREAD

**Issue by RichardAtCT** [jonathanelscpt/valr-python#20]
Hey Jonathan - thanks for the great repo. I am using delete_order to successfully delete an open order, supplying the pair and order_id, however despite the delete going through, I am getting the following API error - any idea? 

`valr_python.exceptions.RESTAPIException: (200, 'valr-python: unknown API error. HTTP (200): Expecting value')
`

**Comment by fatestapestry** [comment]
Thanks, glad to hear that you're finding it useful.

That looks like a bug man.  That shouldn't be throwing an error on a 200
response.  Any additional info would help for a tshoot.

Regards
*Jonathan Els*

**Comment by RichardAtCT** [comment]
Here is the whole error:

`Traceback (most recent call last):
  File "/Library/Python/3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/Users/richardatkinson/Documents/xxx/pages/Valr.py", line 36, in <module>
    st.write(c.delete_order(currency_pair=orders[i]['currencyPair'], order_id=orders[i]['orderId']))
  File "/Library/Python/3.9/site-packages/valr_python/decorators.py", line 16, in inner
    return func(self, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/valr_python/decorators.py", line 33, in inner
    return func(self, *args, **kwargs)
  File "/Library/Python/3.9/site-packages/valr_python/rest_base.py", line 1022, in delete_order
    return self._do('DELETE', '/v1/orders/order', data=data, is_authenticated=True, subaccount_id=subaccount_id)
  File "/Library/Python/3.9/site-packages/valr_python/rest_client.py", line 108, in _do
    raise RESTAPIException(res.status_code,
valr_python.exceptions.RESTAPIException: (200, 'valr-python: unknown API error. HTTP (200): Expecting value')

`

I am looking through the list supplied by the get_all_open_orders() function to delete all my open orders. Not sure what else I can usefully provide! Code looks like this:

`orders = c.get_all_open_orders()
        for i in range(len(orders)):
            st.write(c.delete_order(currency_pair=orders[i]['currencyPair'], order_id=orders[i]['orderId']))`

The 200 API code seems to be the correct one for a successful order delete per the docs?

**Comment by RichardAtCT** [comment]
Having a bit more of a look, I think it is probably because the API is *only* returning a 200 status code and no body which is making your library unhappy. Not sure how to fix that though!

**Comment by RichardAtCT** [comment]
Oh and I installed form the github repo btw so working on the latest version.

**Comment by RichardAtCT** [comment]
Hey @jonathanelscpt - any luck with this?

**Comment by RichardAtCT** [comment]
I looked into this a bit more, what I think is happening is the delete order endpoint doesn't return a request body, which is tripping up the `JSONDecodeError` part of the _do method. I've made a fork and deleted that section and all the references of 'e = res.json()' but that is a bit hacky :)

**Comment by RichardAtCT** [comment]
@jonathanelscpt [Pull Request here](https://github.com/jonathanelscpt/valr-python/pull/21). It is a bit hacky but it works 🤷
