### ISSUE TITLE
Decimal serialization to JSON fails

### ISSUE THREAD

**Issue by jonathanelscpt** [jonathanelscpt/valr-python#8]
When Decimal objects are passed to the SDK, the JSON serialization fails:

```
/home/jonathan/.virtualenvs/valr-instant-bug/bin/python /home/jonathan/.config/JetBrains/PyCharm2020.1/scratches/scratch_16.py
Traceback (most recent call last):
  File "/home/jonathan/.config/JetBrains/PyCharm2020.1/scratches/scratch_16.py", line 11, in <module>
    pprint(valr_client.post_simple_quote(currency_pair='BTCZAR', pay_in_currency='ZAR',
  File "/home/jonathan/develop/valr-python/src/valr_python/decorators.py", line 16, in inner
    return func(self, *args, **kwargs)
  File "/home/jonathan/develop/valr-python/src/valr_python/rest_base.py", line 344, in post_simple_quote
    return self._do('POST', f'/v1/simple/{currency_pair}/quote', data=data, is_authenticated=True)
  File "/home/jonathan/develop/valr-python/src/valr_python/rest_client.py", line 56, in _do
    params = json.loads(json.dumps(data))
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
```

workaround is to use str or float until fixed.

**Comment by jonathanelscpt** [comment]
Will add a decimal encoder subclass of `JSONEncoder` to convert these to strings:

```
class DecimalEncoder(json.JSONEncoder):
    """Serialize Decimal obj as str"""
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            return str(o)
        return super(DecimalEncoder, self).default(o)
```
